### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by jun6lee** [tddschn/homebrew-alfred#1]
Glad to see someone working on a Homebrew workflow.
If you could evolve this in Python3 to something like what the below did, that would really be great.

https://github.com/fniephaus/alfred-homebrew

I've been dabbling at it myself but fumbling with bytes/strings, but then again I'm not that Python3-versed.

**Comment by tddschn** [comment]
I'll look into the repo. :)

This workflow https://github.com/fniephaus/alfred-homebrew is built on https://github.com/deanishe/alfred-workflow, which doesn't have python3 support, at least [for now](http://www.deanishe.net/alfred-workflow/supported-versions.html#python-versions).

I'll try to add more features from https://github.com/fniephaus/alfred-homebrew in the future by implementing them myself. (Already done!)

I installed python2.7 on Monterey to try the workflow you linked, but unfortunately I couldn't make it to work. :(

**Comment by tddschn** [comment]
Now you're able to run brew commands on the selected package! 

Download release 0.2.0 and edit the external script paths and shebangs to try it out. :)

There's also a demo in the readme.

**Comment by jun6lee** [comment]
> I'll look into the repo. :)
> 
> This workflow [fniephaus/alfred-homebrew](https://github.com/fniephaus/alfred-homebrew) is built on [deanishe/alfred-workflow](https://github.com/deanishe/alfred-workflow), which doesn't have python3 support, at least [for now](http://www.deanishe.net/alfred-workflow/supported-versions.html#python-versions).
> 
> I'll try to add more features from [fniephaus/alfred-homebrew](https://github.com/fniephaus/alfred-homebrew) in the future by implementing them myself. (Already done!)


https://github.com/NorthIsUp/alfred-workflow-py3 -- That's where this might also help.
